// <auto-generated />
using System;
using Consultoria.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consultoria.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConsultoriaDbContext))]
    [Migration("20260722023712_AddOptimisticConcurrencyRowVersion")]
    partial class AddOptimisticConcurrencyRowVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Consultoria.Domain.Entities.AreaEspecializacion", b =>
                {
                    b.Property<int>("AreaEspecializacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaEspecializacionId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("AreaEspecializacionId");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UX_AreasEspecializacion_Nombre");

                    b.ToTable("AreasEspecializacion", (string)null);
                });

            modelBuilder.Entity("Consultoria.Domain.Entities.Consultor", b =>
                {
                    b.Property<int>("ConsultorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultorId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("AreaEspecializacionId")
                        .HasColumnType("int");

                    b.Property<string>("EmailCorporativo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TarifaHora")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ConsultorId");

                    b.HasIndex("AreaEspecializacionId")
                        .HasDatabaseName("IX_Consultores_AreaEspecializacionId");

                    b.HasIndex("EmailCorporativo")
                        .IsUnique()
                        .HasDatabaseName("UX_Consultores_EmailCorporativo");

                    b.HasIndex("Nombre", "AreaEspecializacionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Consultores_Nombre_AreaEspecializacionId");

                    b.ToTable("Consultores", null, t =>
                        {
                            t.HasCheckConstraint("CK_Consultores_TarifaHora", "[TarifaHora] >= 30 AND [TarifaHora] <= 200");
                        });
                });

            modelBuilder.Entity("Consultoria.Domain.Entities.PaqueteServicio", b =>
                {
                    b.Property<int>("PaqueteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaqueteId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("AreaEspecializacionId")
                        .HasColumnType("int");

                    b.Property<int>("ConsultorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DuracionHoras")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TarifaHoraAplicada")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PaqueteId");

                    b.HasIndex("AreaEspecializacionId")
                        .HasDatabaseName("IX_PaquetesServicio_AreaEspecializacionId");

                    b.HasIndex("ConsultorId")
                        .HasDatabaseName("IX_PaquetesServicio_ConsultorId");

                    b.HasIndex("AreaEspecializacionId", "Activo")
                        .HasDatabaseName("IX_PaquetesServicio_AreaEspecializacionId_Activo");

                    b.HasIndex("ConsultorId", "Activo")
                        .HasDatabaseName("IX_PaquetesServicio_ConsultorId_Activo");

                    b.ToTable("PaquetesServicio", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaquetesServicio_Costo", "[Costo] > 0");

                            t.HasCheckConstraint("CK_PaquetesServicio_DuracionHoras", "[DuracionHoras] > 0");

                            t.HasCheckConstraint("CK_PaquetesServicio_TarifaHoraAplicada", "[TarifaHoraAplicada] > 0");
                        });
                });

            modelBuilder.Entity("Consultoria.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Usuarios_Email");

                    b.HasIndex("Rol", "Activo")
                        .HasDatabaseName("IX_Usuarios_Rol_Activo");

                    b.ToTable("Usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_Rol", "[Rol] IN ('Admin', 'User')");
                        });
                });

            modelBuilder.Entity("Consultoria.Domain.Entities.Consultor", b =>
                {
                    b.HasOne("Consultoria.Domain.Entities.AreaEspecializacion", null)
                        .WithMany()
                        .HasForeignKey("AreaEspecializacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Consultores_AreasEspecializacion");
                });

            modelBuilder.Entity("Consultoria.Domain.Entities.PaqueteServicio", b =>
                {
                    b.HasOne("Consultoria.Domain.Entities.AreaEspecializacion", null)
                        .WithMany()
                        .HasForeignKey("AreaEspecializacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PaquetesServicio_AreasEspecializacion");

                    b.HasOne("Consultoria.Domain.Entities.Consultor", null)
                        .WithMany()
                        .HasForeignKey("ConsultorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PaquetesServicio_Consultores");
                });
#pragma warning restore 612, 618
        }
    }
}
